version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./requirements:/etc/nginx/templates
    networks:

    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:



  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:


##################################################
volumes:


networks:


