version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    hostname: localhost
    restart: unless-stopped
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wp:/etc/nginx/templates
    networks:
      - wpnet
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306"
    env_file: .env
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wpnet
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - "9000"
    networks:
      - wpnet
    restart: always
    volumes:
      - wp:/var/www/html

##################################################
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/acollin/data/db-data

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/acollin/data/wp

#################################################
networks:
  wpnet:
    driver: bridge
