version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
#    volumes: [db-data:/var/lib/mysql]
    ports:
      - "3306:3306"
    env_file: .env
    restart: always
#    networks: wpnet
#  wordpress:
#    container_name: wordpress
#    build: ./requirements/wordpress/
#    env_file: .env
#    depends_on:
#      - mariadb
#    ports:
#      - "9000:9000"
#    networks:
#      - wpnet
#    restart: always
#    volumes:
#      - wp:/var/www/html
#  nginx:
#    container_name: nginx
#    build: ./requirements/nginx/
#    restart: always
#    depends_on:
#      - wordpress
#    ports:
#      - "443:443"
#    volumes:
#      - wp:/etc/nginx/templates
#    networks:
#      - wpnet
#
###################################################
#volumes:
#  db-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/acollin/data/db-data
#
#  wp:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/acollin/data/wp
#
##################################################
#networks:
#  wpnet:
#    driver: bridge
