version: "3"

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    restart: always
    depends_on: [ wordpress ]
    ports: [ 443:443 ]
    volumes: [ wp:/var/www/ ]
    networks: [ wpnet ]
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes: [ db-data:/var/lib/mysql ]
#    ports: [3306:3306]
    env_file: [ .env ]
    networks: [ wpnet ]
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    env_file: [ .env ]
    depends_on: [ mariadb ]
    volumes: [ wp:/var/www/ ]
#    ports: [9000:9000]
    networks: [ wpnet ]

##################################################
volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/acollin/data/db-data

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/acollin/data/wp

#################################################
networks:
  wpnet:
    driver: bridge
